# Generated by Django 3.2.8 on 2021-10-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Product_id')),
                ('name', models.CharField(max_length=40, verbose_name="Product's name")),
                ('brand', models.CharField(max_length=50, verbose_name='Brand name')),
                ('price', models.FloatField(verbose_name='Product price')),
                ('qty', models.IntegerField(default=1, verbose_name='Quantity')),
                ('warranty', models.IntegerField(default=1, verbose_name='Warranty in months')),
                ('delivery', models.CharField(default='India', max_length=40, verbose_name='delivery_country')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
